spring:
   server:
      remoteserver: http://109.195.86.203:58440/api/
      localserver: http://localhost:8082/
   http:
      multipart:
          max-file-size: 30MB
          max-request-size: 30MB
