spring:
   server:
      remoteserver: http://192.168.1.5:58440/api/
      localserver: http://localhost:8080/
   http:
      multipart:
          max-file-size: 30MB
          max-request-size: 30MB
